name: e_dokan
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

#-------------[PACKAGES START]--------------------

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

#-------------[PACKAGES END]--------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

#-------------[ASSETS]--------------------

assets:
  - assets/logo

#-------------[ASSETS]--------------------

fonts:
  - family: ""
  - fonts:
      - asset: assets/fonts/Nunito-Light.ttf
        weight: 300
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 800
      - asset: assets/fonts/Nunito-Italic.ttf
        style: italic
      - asset: assets/fonts/Nunito-Medium.ttf
        weight: 500
      - asset: assets/fonts/Nunito-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: 400
      - asset: assets/fonts/Nunito-SemiBold.ttf
        weight: 600
